/*
	YPAddCardResponse.h
	The implementation of properties and methods for the YPAddCardResponse object.
	Generated by SudzC.com
*/
#import "YPAddCardResponse.h"

@implementation YPAddCardResponse
	@synthesize cardReference = _cardReference;
	@synthesize fundTransferAllowed = _fundTransferAllowed;
	@synthesize responseMessage = _responseMessage;
	@synthesize statusCode = _statusCode;
	@synthesize valid = _valid;

	- (id) init
	{
		if(self = [super init])
		{
			self.cardReference = nil;
			self.fundTransferAllowed = nil;
			self.responseMessage = nil;

		}
		return self;
	}

-(void)parsingAddcard:(NSDictionary*)dictResponse{
    
    NSLog(@"parsingAddcard = %@",dictResponse);
    
    /*NSLog(@"string of ststus code %@",[[[[dictResponse valueForKey:@"addCardResponse"] valueForKey:@"addCardReturn"] valueForKey:@"statusCode"] valueForKey:@"text"]);
     NSLog(@"status code is %d",self.statusCode);
     
     self.statusCode=[[[[[dictResponse valueForKey:@"addCardResponse"] valueForKey:@"addCardReturn"] valueForKey:@"statusCode"] valueForKey:@"text"]intValue];
     
     self.responseMessage=[[[[dictResponse valueForKey:@"addCardResponse"] valueForKey:@"addCardReturn"] valueForKey:@"responseMessage"] valueForKey:@"text"];*/
    
    
    NSLog(@"string of ststus code %@",[[[[dictResponse valueForKey:@"addCardResponse"] valueForKey:@"addCardReturn"] valueForKey:@"statusCode"] valueForKey:@"text"]);
    NSLog(@"status code is %d",self.statusCode);
    
    self.statusCode=[[[[[dictResponse valueForKey:@"addCardResponse"] valueForKey:@"ns1:addCardReturn"] valueForKey:@"ns1:statusCode"] valueForKey:@"text"]intValue];
    
    self.responseMessage=[[[[dictResponse valueForKey:@"addCardResponse"] valueForKey:@"ns1:addCardReturn"] valueForKey:@"ns1:responseMessage"] valueForKey:@"text"];
    
    
    
    NSLog(@"status code is %d",self.statusCode);
    
}@end
