/*
	YPAddCardRequest.h
	The implementation of properties and methods for the YPAddCardRequest object.
	Generated by SudzC.com
*/
#import "YPAddCardRequest.h"

@implementation YPAddCardRequest
	@synthesize CVV = _CVV;
	@synthesize SC = _SC;
	@synthesize addressLine1 = _addressLine1;
	@synthesize addressLine2 = _addressLine2;
	@synthesize applicationType = _applicationType;
	@synthesize cardIssueNumber = _cardIssueNumber;
	@synthesize cardName = _cardName;
	@synthesize cardNumber = _cardNumber;
	@synthesize cardholderName = _cardholderName;
	@synthesize city = _city;
	@synthesize country = _country;
	@synthesize email1 = _email1;
	@synthesize expiryDate = _expiryDate;
	@synthesize fax1 = _fax1;
	@synthesize phone1 = _phone1;
	@synthesize postCode = _postCode;
	@synthesize startDate = _startDate;
	@synthesize userName = _userName;
	@synthesize valid = _valid;



	- (id) init
	{
		if(self = [super init])
		{
			self.CVV = nil;
			self.SC = nil;
			self.addressLine1 = nil;
			self.addressLine2 = nil;
			self.applicationType = nil;
			self.cardIssueNumber = nil;
			self.cardName = nil;
			self.cardNumber = nil;
			self.cardholderName = nil;
			self.city = nil;
			self.country = nil;
			self.email1 = nil;
			self.expiryDate = nil;
			self.fax1 = nil;
			self.phone1 = nil;
			self.postCode = nil;
			self.startDate = nil;
			self.userName = nil;
		}
		return self;
	}

	

@end
