/*
	YPAddCardRequest.h
	The interface definition of properties and methods for the YPAddCardRequest object.
	Generated by SudzC.com
*/

#import <Foundation/Foundation.h>


@interface YPAddCardRequest : NSObject
{
	NSString* _CVV;
	NSString* _SC;
	NSString* _addressLine1;
	NSString* _addressLine2;
	NSString* _applicationType;
	NSString* _cardIssueNumber;
	NSString* _cardName;
	NSString* _cardNumber;
	NSString* _cardholderName;
	NSString* _city;
	NSString* _country;
	NSString* _email1;
	NSString* _expiryDate;
	NSString* _fax1;
	NSString* _phone1;
	NSString* _postCode;
	NSString* _startDate;
	NSString* _userName;
    NSString* _profilePic;
	BOOL _valid;
	
}
		
	@property (strong, nonatomic) NSString* CVV;
	@property (strong, nonatomic) NSString* SC;
	@property (strong, nonatomic) NSString* addressLine1;
	@property (strong, nonatomic) NSString* addressLine2;
	@property (strong, nonatomic) NSString* applicationType;
	@property (strong, nonatomic) NSString* cardIssueNumber;
	@property (strong, nonatomic) NSString* cardName;
	@property (strong, nonatomic) NSString* cardNumber;
	@property (strong, nonatomic) NSString* cardholderName;
	@property (strong, nonatomic) NSString* city;
	@property (strong, nonatomic) NSString* country;
	@property (strong, nonatomic) NSString* email1;
	@property (strong, nonatomic) NSString* expiryDate;
	@property (strong, nonatomic) NSString* fax1;
	@property (strong, nonatomic) NSString* phone1;
	@property (strong, nonatomic) NSString* postCode;
	@property (strong, nonatomic) NSString* startDate;
	@property (strong, nonatomic) NSString* userName;
	@property BOOL valid;

	

@end
