/*
	YPAddCardResponse.h
	The interface definition of properties and methods for the YPAddCardResponse object.
	Generated by SudzC.com
*/

#import <Foundation/Foundation.h>


@interface YPAddCardResponse : NSObject
{
	NSString* _cardReference;
	NSString* _fundTransferAllowed;
	NSString* _responseMessage;
	int _statusCode;
	BOOL _valid;
	
}
		
	@property (strong, nonatomic) NSString* cardReference;
	@property (strong, nonatomic) NSString* fundTransferAllowed;
	@property (strong, nonatomic) NSString* responseMessage;
	@property int statusCode;
	@property BOOL valid;

-(void)parsingAddcard:(NSDictionary*)dictResponse;


@end
