/*
	YPCardInWalletDetailed.h
	The implementation of properties and methods for the YPCardInWalletDetailed object.
	Generated by SudzC.com
*/
#import "YPCardInWalletDetailed.h"

@implementation YPCardInWalletDetailed
	@synthesize addressLine1 = _addressLine1;
	@synthesize addressLine2 = _addressLine2;
	@synthesize balance = _balance;
	@synthesize cardIssueNumber = _cardIssueNumber;
	@synthesize cardName = _cardName;
	@synthesize cardNumber = _cardNumber;
	@synthesize cardReference = _cardReference;
	@synthesize cardholderName = _cardholderName;
	@synthesize city = _city;
	@synthesize country = _country;
	@synthesize email1 = _email1;
	@synthesize expiryDate = _expiryDate;
	@synthesize fax1 = _fax1;
	@synthesize fundTransferAllowed = _fundTransferAllowed;
	@synthesize issuerImageURL = _issuerImageURL;
	@synthesize issuerName = _issuerName;
	@synthesize phone1 = _phone1;
	@synthesize postCode = _postCode;
	@synthesize startDate = _startDate;
	@synthesize status = _status;
	@synthesize valid = _valid;

	- (id) init
	{
		if(self = [super init])
		{
			self.addressLine1 = nil;
			self.addressLine2 = nil;
			self.cardIssueNumber = nil;
			self.cardName = nil;
			self.cardNumber = nil;
			self.cardReference = nil;
			self.cardholderName = nil;
			self.city = nil;
			self.country = nil;
			self.email1 = nil;
			self.expiryDate = nil;
			self.fax1 = nil;
			self.fundTransferAllowed = nil;
			self.issuerImageURL = nil;
			self.issuerName = nil;
			self.phone1 = nil;
			self.postCode = nil;
			self.startDate = nil;
			self.status = nil;

		}
		return self;
	}

	

@end
