/*
	YPCardInfo.h
	The interface definition of properties and methods for the YPCardInfo object.
	Generated by SudzC.com
*/

#import <Foundation/Foundation.h>


@interface YPCardInfo : NSObject
{
//	NSString* _CVV;
	NSString* _cardIssueNumber;
	NSString* _cardName;
	NSString* _cardNumber;
	NSString* _expiryDate;
	NSString* _fax;
	NSString* _issuerId;
	NSString* _startDate;
	BOOL _valid;
	
}
		
	@property (strong, nonatomic) NSString* CVV;
	@property (strong, nonatomic) NSString* cardIssueNumber;
	@property (strong, nonatomic) NSString* cardName;
	@property (strong, nonatomic) NSString* cardNumber;
	@property (strong, nonatomic) NSString* expiryDate;
	@property (strong, nonatomic) NSString* fax;
	@property (strong, nonatomic) NSString* issuerId;
	@property (strong, nonatomic) NSString* startDate;
	@property BOOL valid;

	

@end
