/*
	YPCardInWalletDetailed.h
	The interface definition of properties and methods for the YPCardInWalletDetailed object.
	Generated by SudzC.com
*/

#import <Foundation/Foundation.h>
	

@interface YPCardInWalletDetailed : NSObject
{
	NSString* _addressLine1;
	NSString* _addressLine2;
	int _balance;
	NSString* _cardIssueNumber;
	NSString* _cardName;
	NSString* _cardNumber;
	NSString* _cardReference;
	NSString* _cardholderName;
	NSString* _city;
	NSString* _country;
	NSString* _email1;
	NSString* _expiryDate;
	NSString* _fax1;
	NSString* _fundTransferAllowed;
	NSString* _issuerImageURL;
	NSString* _issuerName;
	NSString* _phone1;
	NSString* _postCode;
	NSString* _startDate;
	NSString* _status;
	BOOL _valid;
	
}
		
	@property (strong, nonatomic) NSString* addressLine1;
	@property (strong, nonatomic) NSString* addressLine2;
	@property int balance;
	@property (strong, nonatomic) NSString* cardIssueNumber;
	@property (strong, nonatomic) NSString* cardName;
	@property (strong, nonatomic) NSString* cardNumber;
	@property (strong, nonatomic) NSString* cardReference;
	@property (strong, nonatomic) NSString* cardholderName;
	@property (strong, nonatomic) NSString* city;
	@property (strong, nonatomic) NSString* country;
	@property (strong, nonatomic) NSString* email1;
	@property (strong, nonatomic) NSString* expiryDate;
	@property (strong, nonatomic) NSString* fax1;
	@property (strong, nonatomic) NSString* fundTransferAllowed;
	@property (strong, nonatomic) NSString* issuerImageURL;
	@property (strong, nonatomic) NSString* issuerName;
	@property (strong, nonatomic) NSString* phone1;
	@property (strong, nonatomic) NSString* postCode;
	@property (strong, nonatomic) NSString* startDate;
	@property (strong, nonatomic) NSString* status;
	@property BOOL valid;



@end
