/*
	YPCardInfo.h
	The implementation of properties and methods for the YPCardInfo object.
	Generated by SudzC.com
*/
#import "YPCardInfo.h"

@implementation YPCardInfo

    @synthesize CVV;
	@synthesize cardIssueNumber = _cardIssueNumber;
	@synthesize cardName = _cardName;
	@synthesize cardNumber = _cardNumber;
	@synthesize expiryDate = _expiryDate;
	@synthesize fax = _fax;
	@synthesize issuerId = _issuerId;
	@synthesize startDate = _startDate;
	@synthesize valid = _valid;

	- (id) init
	{
		if(self = [super init])
		{
			self.CVV = nil;
			self.cardIssueNumber = nil;
			self.cardName = nil;
			self.cardNumber = nil;
			self.expiryDate = nil;
			self.fax = nil;
			self.issuerId = nil;
			self.startDate = nil;

		}
		return self;
	}

	
@end
