/*
	YPCountryListRequest.h
	The implementation of properties and methods for the YPCountryListRequest object.
	Generated by SudzC.com
*/
#import "YPCountryListRequest.h"

@implementation YPCountryListRequest
	@synthesize SC = _SC;
	@synthesize applicationType = _applicationType;
	@synthesize userName = _userName;
	@synthesize valid = _valid;

	- (id) init
	{
		if(self = [super init])
		{
			self.SC = nil;
			self.applicationType = nil;
			self.userName = nil;

		}
		return self;
	}




@end
