/*
	YPCountryListResponse.h
	The interface definition of properties and methods for the YPCountryListResponse object.
	Generated by SudzC.com
*/

#import <Foundation/Foundation.h>

@class YPCountryList;

@interface YPCountryListResponse : NSObject
{
	NSMutableArray* _countryList;
	NSString* _responseMessage;
	int _statusCode;
	BOOL _valid;
	
}
		
@property (strong, nonatomic) NSMutableArray* countryList;
@property (strong, nonatomic) NSString* responseMessage;
@property int statusCode;
@property BOOL valid;

-(void)parsingCountryList:(NSDictionary*)dictResponse;



@end
