/*
	YPCurrencyCodesResponse.h
	The interface definition of properties and methods for the YPCurrencyCodesResponse object.
	Generated by SudzC.com
*/

#import <Foundation/Foundation.h>


@interface YPCurrencyCodesResponse : NSObject
{
	NSMutableArray* _currencyCodeList;
	NSString* _responseMessage;
	int _statusCode;
	BOOL _valid;
	
}
		
	@property (strong, nonatomic) NSMutableArray* currencyCodeList;
	@property (strong, nonatomic) NSString* responseMessage;
	@property int statusCode;
	@property BOOL valid;

-(void)parsingCurrencyList:(NSDictionary*)dictResponse;



@end
