/*
	YPCurrencyCodeDetails.h
	The implementation of properties and methods for the YPCurrencyCodeDetails object.
	Generated by SudzC.com
*/
#import "YPCurrencyCodeDetails.h"

@implementation YPCurrencyCodeDetails
	@synthesize currencyAlphaCode = _currencyAlphaCode;
	@synthesize currencyCode = _currencyCode;
	@synthesize currencyName = _currencyName;
	@synthesize valid = _valid;

	- (id) init
	{
		if(self = [super init])
		{
			self.currencyAlphaCode = nil;
			self.currencyCode = nil;
			self.currencyName = nil;

		}
		return self;
	}

	
@end
