/*
	YPCurrencyCodesRequest.h
	The implementation of properties and methods for the YPCurrencyCodesRequest object.
	Generated by SudzC.com
*/
#import "YPCurrencyCodesRequest.h"

@implementation YPCurrencyCodesRequest
	@synthesize SC = _SC;
	@synthesize applicationType = _applicationType;
	@synthesize userName = _userName;
	@synthesize valid = _valid;

	- (id) init
	{
		if(self = [super init])
		{
			self.SC = nil;
			self.applicationType = nil;
			self.userName = nil;

		}
		return self;
	}

	

@end
