/*
	YPCurrencyCodesRequest.h
	The interface definition of properties and methods for the YPCurrencyCodesRequest object.
	Generated by SudzC.com
*/

#import <Foundation/Foundation.h>


@interface YPCurrencyCodesRequest : NSObject
{
	NSString* _SC;
	NSString* _applicationType;
	NSString* _userName;
	BOOL _valid;
	
}
		
	@property (strong, nonatomic) NSString* SC;
	@property (strong, nonatomic) NSString* applicationType;
	@property (strong, nonatomic) NSString* userName;
	@property BOOL valid;


@end
