/*
	YPCurrencyCodeDetails.h
	The interface definition of properties and methods for the YPCurrencyCodeDetails object.
	Generated by SudzC.com
*/

#import <Foundation/Foundation.h>


@interface YPCurrencyCodeDetails : NSObject
{
	NSString* _currencyAlphaCode;
	NSString* _currencyCode;
	NSString* _currencyName;
	BOOL _valid;
	
}
		
	@property (strong, nonatomic) NSString* currencyAlphaCode;
	@property (strong, nonatomic) NSString* currencyCode;
	@property (strong, nonatomic) NSString* currencyName;
	@property BOOL valid;



@end
