/*
	YPGetCardsInWalletDetailedRequest.h
	The implementation of properties and methods for the YPGetCardsInWalletDetailedRequest object.
	Generated by SudzC.com
*/
#import "YPGetCardsInWalletDetailedRequest.h"

@implementation YPGetCardsInWalletDetailedRequest
	@synthesize SC = _SC;
	@synthesize applicationType = _applicationType;
	@synthesize updateDatetimestamp = _updateDatetimestamp;
	@synthesize userName = _userName;
	@synthesize valid = _valid;

	- (id) init
	{
		if(self = [super init])
		{
			self.SC = nil;
			self.applicationType = nil;
			self.updateDatetimestamp = nil;
			self.userName = nil;

		}
		return self;
	}



@end
