/*
 YPGetCardsInWalletDetailedResponse.h
 The implementation of properties and methods for the YPGetCardsInWalletDetailedResponse object.
 Generated by SudzC.com
 */
#import "YPGetCardsInWalletDetailedResponse.h"
#import "CardDetailsData.h"
#import "YPCardInWalletDetailed.h"



@implementation YPGetCardsInWalletDetailedResponse
@synthesize cardDetailedList = _cardDetailedList;
@synthesize responseMessage = _responseMessage;
@synthesize statusCode = _statusCode;
@synthesize updateDatetimestamp = _updateDatetimestamp;
@synthesize valid = _valid;

- (id) init
{
    if(self = [super init])
    {
        self.cardDetailedList = [[NSMutableArray alloc] init];
        self.responseMessage = nil;
        self.updateDatetimestamp = nil;
        
    }
    return self;
}

-(void)parsingGetCards:(NSDictionary*)dictResponse{
    
    NSLog(@"parsingGetCards  = %@",dictResponse);
    
    self.statusCode=[[[[[dictResponse valueForKey:@"getCardsInWalletDetailedResponse"] valueForKey:@"getCardsInWalletDetailedReturn"] valueForKey:@"statusCode"] valueForKey:@"text"]intValue];
    
    self.responseMessage=[[[[dictResponse valueForKey:@"getCardsInWalletDetailedResponse"] valueForKey:@"getCardsInWalletDetailedReturn"] valueForKey:@"responseMessage"] valueForKey:@"text"];
    
    self.updateDatetimestamp=[[[[dictResponse valueForKey:@"getCardsInWalletDetailedResponse"] valueForKey:@"getCardsInWalletDetailedReturn"] valueForKey:@"updateDatetimestamp"] valueForKey:@"text"];
    
    
    
    NSLog(@"%@",[[[dictResponse valueForKey:@"getCardsInWalletDetailedResponse"] valueForKey:@"getCardsInWalletDetailedReturn"] valueForKey:@"cardDetailedList"]);
    
    
    int counter=[[[[[[dictResponse valueForKey:@"getCardsInWalletDetailedResponse"] valueForKey:@"getCardsInWalletDetailedReturn"] valueForKey:@"cardDetailedList"] valueForKey:@"cardInWalletDetailedCount"] valueForKey:@"text"] intValue];
    
    NSLog(@"counter = %d",counter);
    
    NSLog(@"value is====== %@",[ [[[dictResponse valueForKey:@"getCardsInWalletDetailedResponse"] valueForKey:@"getCardsInWalletDetailedReturn"] valueForKey:@"cardDetailedList"] valueForKey:@"cardInWalletDetailed"]);
    for (int i=0; i<counter; i++) {
         NSLog(@"card details - %@",[[[[dictResponse valueForKey:@"getCardsInWalletDetailedResponse"] valueForKey:@"getCardsInWalletDetailedReturn"] valueForKey:@"cardDetailedList"] valueForKey:@"cardInWalletDetailed"]) ;
        
      CardDetailsData *object=[[CardDetailsData alloc] init];
        
        object.address1=[[[[[[dictResponse valueForKey:@"getCardsInWalletDetailedResponse"] valueForKey:@"getCardsInWalletDetailedReturn"] valueForKey:@"cardDetailedList"] valueForKey:@"cardInWalletDetailed"]  valueForKey:@"addressLine1"] valueForKey:@"text"];
        NSLog(@"value of addressline 1 is %@",object.address1);
        
        object.address2=[[[[[[dictResponse valueForKey:@"getCardsInWalletDetailedResponse"] valueForKey:@"getCardsInWalletDetailedReturn"] valueForKey:@"cardDetailedList"] valueForKey:@"cardInWalletDetailed"]  valueForKey:@"addressLine2"] valueForKey:@"text"];
        
        object.cardBalance=[[[[[[dictResponse valueForKey:@"getCardsInWalletDetailedResponse"] valueForKey:@"getCardsInWalletDetailedReturn"] valueForKey:@"cardDetailedList"] valueForKey:@"cardInWalletDetailed"] valueForKey:@"balance"] valueForKey:@"text"];
        
        object.issuerName=[[[[[[dictResponse valueForKey:@"getCardsInWalletDetailedResponse"] valueForKey:@"getCardsInWalletDetailedReturn"] valueForKey:@"cardDetailedList"] valueForKey:@"cardInWalletDetailed"]  valueForKey:@"cardIssueNumber"] valueForKey:@"text"];
        
        object.cardname=[[[[[[dictResponse valueForKey:@"getCardsInWalletDetailedResponse"] valueForKey:@"getCardsInWalletDetailedReturn"] valueForKey:@"cardDetailedList"] valueForKey:@"cardInWalletDetailed"]  valueForKey:@"cardName"] valueForKey:@"text"];
        
        object.cardnumber=[[[[[[dictResponse valueForKey:@"getCardsInWalletDetailedResponse"] valueForKey:@"getCardsInWalletDetailedReturn"] valueForKey:@"cardDetailedList"] valueForKey:@"cardInWalletDetailed"] valueForKey:@"cardNumber"] valueForKey:@"text"];
        
        object.cardReferance=[[[[[[dictResponse valueForKey:@"getCardsInWalletDetailedResponse"] valueForKey:@"getCardsInWalletDetailedReturn"] valueForKey:@"cardDetailedList"] valueForKey:@"cardInWalletDetailed"] valueForKey:@"cardReference"] valueForKey:@"text"];
        NSLog(@"***=cardReference=%@",object.cardReferance);
        object.cardholdername=[[[[[[dictResponse valueForKey:@"getCardsInWalletDetailedResponse"] valueForKey:@"getCardsInWalletDetailedReturn"] valueForKey:@"cardDetailedList"] valueForKey:@"cardInWalletDetailed"]  valueForKey:@"cardholderName"] valueForKey:@"text"];
        
        object.city=[[[[[[dictResponse valueForKey:@"getCardsInWalletDetailedResponse"] valueForKey:@"getCardsInWalletDetailedReturn"] valueForKey:@"cardDetailedList"] valueForKey:@"cardInWalletDetailed"]  valueForKey:@"city"] valueForKey:@"text"];
        
        object.country=[[[[[[dictResponse valueForKey:@"getCardsInWalletDetailedResponse"] valueForKey:@"getCardsInWalletDetailedReturn"] valueForKey:@"cardDetailedList"] valueForKey:@"cardInWalletDetailed"]  valueForKey:@"country"] valueForKey:@"text"];
        
        object.email1=[[[[[[dictResponse valueForKey:@"getCardsInWalletDetailedResponse"] valueForKey:@"getCardsInWalletDetailedReturn"] valueForKey:@"cardDetailedList"] valueForKey:@"cardInWalletDetailed"]  valueForKey:@"email1"] valueForKey:@"text"];
   
        object.expiryDate=[[[[[[dictResponse valueForKey:@"getCardsInWalletDetailedResponse"] valueForKey:@"getCardsInWalletDetailedReturn"] valueForKey:@"cardDetailedList"] valueForKey:@"cardInWalletDetailed"]  valueForKey:@"expiryDate"] valueForKey:@"text"];
        
        object.fax1=[[[[[[dictResponse valueForKey:@"getCardsInWalletDetailedResponse"] valueForKey:@"getCardsInWalletDetailedReturn"] valueForKey:@"cardDetailedList"] valueForKey:@"cardInWalletDetailed"]  valueForKey:@"fax1"] valueForKey:@"text"];
        
        NSLog(@"fax is===== %@",object.fax1);
        
        object.fundtransferallowed=[[[[[[dictResponse valueForKey:@"getCardsInWalletDetailedResponse"] valueForKey:@"getCardsInWalletDetailedReturn"] valueForKey:@"cardDetailedList"] valueForKey:@"cardInWalletDetailed"]valueForKey:@"fundTransferAllowed"] valueForKey:@"text"];
        
        object.issuerImageURL=[[[[[[dictResponse valueForKey:@"getCardsInWalletDetailedResponse"] valueForKey:@"getCardsInWalletDetailedReturn"] valueForKey:@"cardDetailedList"] valueForKey:@"cardInWalletDetailed"] valueForKey:@"issuerImageURL"] valueForKey:@"text"];
        
        object.issuerName=[[[[[[dictResponse valueForKey:@"getCardsInWalletDetailedResponse"] valueForKey:@"getCardsInWalletDetailedReturn"] valueForKey:@"cardDetailedList"] valueForKey:@"cardInWalletDetailed"]  valueForKey:@"issuerName"] valueForKey:@"text"];
        
        object.phone1=[[[[[[dictResponse valueForKey:@"getCardsInWalletDetailedResponse"] valueForKey:@"getCardsInWalletDetailedReturn"] valueForKey:@"cardDetailedList"] valueForKey:@"cardInWalletDetailed"]  valueForKey:@"phone1"] valueForKey:@"text"];
        
        object.postcode=[[[[[[dictResponse valueForKey:@"getCardsInWalletDetailedResponse"] valueForKey:@"getCardsInWalletDetailedReturn"] valueForKey:@"cardDetailedList"] valueForKey:@"cardInWalletDetailed"]  valueForKey:@"postCode"] valueForKey:@"text"];
        
        object.startdate=[[[[[[dictResponse valueForKey:@"getCardsInWalletDetailedResponse"] valueForKey:@"getCardsInWalletDetailedReturn"] valueForKey:@"cardDetailedList"] valueForKey:@"cardInWalletDetailed"]  valueForKey:@"startDate"] valueForKey:@"text"];
        
        object.cardStatus=[[[[[[dictResponse valueForKey:@"getCardsInWalletDetailedResponse"] valueForKey:@"getCardsInWalletDetailedReturn"] valueForKey:@"cardDetailedList"] valueForKey:@"cardInWalletDetailed"] valueForKey:@"status"] valueForKey:@"text"];
        
        [self.cardDetailedList addObject:object];
        
        
    }
    
    
    
}


@end
