/*
	YPLogoutRequest.h
	The implementation of properties and methods for the YPLogoutRequest object.
	Generated by SudzC.com
*/
#import "YPLogoutRequest.h"

@implementation YPLogoutRequest
	@synthesize SC = _SC;
	@synthesize applicationType = _applicationType;
	@synthesize role = _role;
	@synthesize userName = _userName;
	@synthesize valid = _valid;

	- (id) init
	{
		if(self = [super init])
		{
			self.SC = nil;
			self.applicationType = nil;
			self.role = nil;
			self.userName = nil;

		}
		return self;
	}

	
@end
