/*
	YPLogoutResponse.h
	The implementation of properties and methods for the YPLogoutResponse object.
	Generated by SudzC.com
*/
#import "YPLogoutResponse.h"

@implementation YPLogoutResponse
	@synthesize responseMessage = _responseMessage;
	@synthesize statusCode = _statusCode;
	@synthesize valid = _valid;

	- (id) init
	{
		if(self = [super init])
		{
			self.responseMessage = nil;

		}
		return self;
	}

-(void)parsingLogout:(NSDictionary*)dictResponse{
    
    self.statusCode=[[[[[dictResponse valueForKey:@"logoutShopperResponse"] valueForKey:@"logoutShopperReturn"] valueForKey:@"statusCode"] valueForKey:@"text"]
                     intValue];
    
    self.responseMessage=[[[[dictResponse valueForKey:@"logoutShopperResponse"] valueForKey:@"logoutShopperReturn"] valueForKey:@"responseMessage"] valueForKey:@"text"];
    
}




@end
