/*
	YPLoginResponse.h
	The implementation of properties and methods for the YPLoginResponse object.
	Generated by SudzC.com
*/
#import "YPLoginResponse.h"

@implementation YPLoginResponse
	@synthesize SC = _SC;
	@synthesize lastLoginDate = _lastLoginDate;
	@synthesize lastLoginTime = _lastLoginTime;
	@synthesize mustChangePassword = _mustChangePassword;
	@synthesize responseMessage = _responseMessage;
	@synthesize statusCode = _statusCode;
	@synthesize valid = _valid;

	- (id) init
	{
		if(self = [super init])
		{
			self.SC = nil;
			self.lastLoginDate = nil;
			self.lastLoginTime = nil;
			self.responseMessage = nil;

		}
		return self;
	}

-(void)parsingLogin:(NSDictionary*)dictResponse{
    
    NSLog(@"DICT RESPONSE : %@",dictResponse);
    
    
    
    //New implementation added by sumit on 18 march
    
    
    //    NSLog(@"%@",[dictResponse valueForKey:@"loginShopperResponse"]);
    //    NSLog(@"%@",[[dictResponse valueForKey:@"loginShopperResponse"] valueForKey:@"ns1:loginShopperReturn"]);
    //    NSLog(@"%@",[[[dictResponse valueForKey:@"loginShopperResponse"] valueForKey:@"ns1:loginShopperReturn"] valueForKey:@"ns1:SC"]);
    //    NSLog(@"%@",[[[[dictResponse valueForKey:@"loginShopperResponse"] valueForKey:@"ns1:loginShopperReturn"] valueForKey:@"ns1:SC"] valueForKey:@"text"]);
    
    self.SC=[[[[dictResponse valueForKey:@"loginShopperResponse"] valueForKey:@"ns1:loginShopperReturn"] valueForKey:@"ns1:SC"] valueForKey:@"text"];
    
    
    
    
    self.statusCode=[[[[[dictResponse valueForKey:@"loginShopperResponse"] valueForKey:@"ns1:loginShopperReturn"] valueForKey:@"ns1:statusCode"] valueForKey:@"text"]
                     intValue];
    
    self.responseMessage=[[[[dictResponse valueForKey:@"loginShopperResponse"] valueForKey:@"ns1:loginShopperReturn"] valueForKey:@"ns1:responseMessage"] valueForKey:@"text"];
    
    
    
    
    
    
    
}

@end
