/*
	YPLoginResponse.h
	The interface definition of properties and methods for the YPLoginResponse object.
	Generated by SudzC.com
*/

#import <Foundation/Foundation.h>

@interface YPLoginResponse : NSObject
{
	NSString* _SC;
	NSString* _lastLoginDate;
	NSString* _lastLoginTime;
	BOOL _mustChangePassword;
	NSString* _responseMessage;
	int _statusCode;
	BOOL _valid;
	
}
		
	@property (strong, nonatomic) NSString* SC;
	@property (strong, nonatomic) NSString* lastLoginDate;
	@property (strong, nonatomic) NSString* lastLoginTime;
	@property BOOL mustChangePassword;
	@property (strong, nonatomic) NSString* responseMessage;
	@property int statusCode;
	@property BOOL valid;

-(void)parsingLogin:(NSDictionary*)dictResponse;

@end
