/*
	YPLogoutRequest.h
	The interface definition of properties and methods for the YPLogoutRequest object.
	Generated by SudzC.com
*/

#import <Foundation/Foundation.h>


@interface YPLogoutRequest : NSObject
{
	NSString* _SC;
	NSString* _applicationType;
	NSString* _role;
	NSString* _userName;
	BOOL _valid;
	
}
		
	@property (strong, nonatomic) NSString* SC;
	@property (strong, nonatomic) NSString* applicationType;
	@property (strong, nonatomic) NSString* role;
	@property (strong, nonatomic) NSString* userName;
	@property BOOL valid;



@end
