/*
	YPLoginRequest.h
	The interface definition of properties and methods for the YPLoginRequest object.
	Generated by SudzC.com
*/

#import <Foundation/Foundation.h>


@interface YPLoginRequest : NSObject
{
	NSString* _applicationType;
	NSString* _mobileIdentificationNumber;
	NSString* _password;
	NSString* _role;
	NSString* _userName;
    NSString* _versionID;
    BOOL _valid;
	
}
		
	@property (strong, nonatomic) NSString* applicationType;
	@property (strong, nonatomic) NSString* mobileIdentificationNumber;
	@property (strong, nonatomic) NSString* password;
	@property (strong, nonatomic) NSString* role;
	@property (strong, nonatomic) NSString* userName;
    @property (strong, nonatomic) NSString* versionID;
	@property BOOL valid;


@end
