/*
	YPRemoveCardRequest.h
	The interface definition of properties and methods for the YPRemoveCardRequest object.
	Generated by SudzC.com
*/

#import <Foundation/Foundation.h>


@interface YPRemoveCardRequest : NSObject
{
	NSString* _SC;
	NSString* _applicationType;
	NSString* _cardName;
	NSString* _cardReference;
	NSString* _userName;
	BOOL _valid;
	
}
		
	@property (strong, nonatomic) NSString* SC;
	@property (strong, nonatomic) NSString* applicationType;
	@property (strong, nonatomic) NSString* cardName;
	@property (strong, nonatomic) NSString* cardReference;
	@property (strong, nonatomic) NSString* userName;
	@property BOOL valid;


@end
