/*
	YPRemoveCardResponse.h
	The interface definition of properties and methods for the YPRemoveCardResponse object.
	Generated by SudzC.com
*/

#import <Foundation/Foundation.h>


@interface YPRemoveCardResponse : NSObject
{
	NSString* _responseMessage;
	int _statusCode;
	BOOL _valid;
	
}
		
	@property (strong, nonatomic) NSString* responseMessage;
	@property int statusCode;
	@property BOOL valid;

-(void)parsingDeleteCard:(NSDictionary*)dictResponse;



@end
