/*
	YPRegisterRequest.h
	The interface definition of properties and methods for the YPRegisterRequest object.
	Generated by SudzC.com
*/

#import <Foundation/Foundation.h>
#import "YPCardInfo.h"


@interface YPRegisterRequest : NSObject
{
	NSString* DOB;
    NSString* firstName;

    NSString* gender;
	NSString* lastName;
	NSString* password;
    NSString* profilePic;
    NSString* profilePictureName;
    
	NSString* userID;
    BOOL valid;

	NSString* versionID;
	
}
		
	@property (strong, nonatomic) NSString* DOB;
	@property (strong, nonatomic) NSString* firstName;
    @property (strong, nonatomic) NSString* gender;
    @property (strong, nonatomic) NSString* lastName;
    @property (strong, nonatomic) NSString* password;
    @property (strong, nonatomic) NSString* profilePic;
    @property (strong, nonatomic) NSString* profilePictureName;
    @property (strong, nonatomic) NSString* userID;
    @property BOOL valid;
    @property (strong, nonatomic) NSString* versionID;

	

@end
