/*
	YPRegisterResponse.h
	The implementation of properties and methods for the YPRegisterResponse object.
	Generated by SudzC.com
*/
#import "YPRegisterResponse.h"

@implementation YPRegisterResponse

	@synthesize fundTransferAllowed = _fundTransferAllowed;
	@synthesize responseMessage = _responseMessage;
	@synthesize statusCode = _statusCode;
	@synthesize valid = _valid;

	- (id) init
	{
		if(self = [super init])
		{
			self.fundTransferAllowed = nil;
			self.responseMessage = nil;

		}
		return self;
	}
-(void)parsingRegistration:(NSDictionary*)dictResponse{

    NSLog(@"parsingRegistration = %@",dictResponse);
    
    NSLog(@"%@",[dictResponse valueForKey:@"registerUserResponse"]);
    
    self.statusCode=[[[[[dictResponse valueForKey:@"registerUserResponse"] valueForKey:@"registerUserReturn"] valueForKey:@"statusCode"] valueForKey:@"text"]intValue];
    
    
    self.responseMessage=[[[[dictResponse valueForKey:@"registerUserResponse"] valueForKey:@"registerUserReturn"] valueForKey:@"responseMessage"] valueForKey:@"text"];
    

}


@end
