/*
	YPRegisterResponse.h
	The interface definition of properties and methods for the YPRegisterResponse object.
	Generated by SudzC.com
*/

#import <Foundation/Foundation.h>


@interface YPRegisterResponse : NSObject
{
	NSString* _fundTransferAllowed;
	NSString* _responseMessage;
	int _statusCode;
	BOOL _valid;
	
}
		
	@property (strong, nonatomic) NSString* fundTransferAllowed;
	@property (strong, nonatomic) NSString* responseMessage;
	@property int statusCode;
	@property BOOL valid;

-(void)parsingRegistration:(NSDictionary*)dictResponse;	

@end
