/*
	YPRegisterRequest.h
	The implementation of properties and methods for the YPRegisterRequest object.
	Generated by SudzC.com
*/
#import "YPRegisterRequest.h"

#import "YPCardInfo.h"

@implementation YPRegisterRequest
	@synthesize DOB = _DOB;
	@synthesize firstName = _firstName;
    @synthesize gender = _gender;
    @synthesize lastName = _lastName;
    @synthesize password  = _password;
    @synthesize profilePic = _profilePic;
    @synthesize profilePictureName = _profilePictureName;
    @synthesize userID = _userID;
	@synthesize valid = _valid;
    @synthesize versionID = _versionID;

	- (id) init
	{
		if(self = [super init])
		{
			self.DOB = nil;
            self.firstName = nil;
            self.gender=nil;
			self.lastName = nil;
			self.password = nil;
            self.profilePic = nil;
            self.profilePictureName=nil;
            self.userID=nil;
            self.versionID=nil;
            
            
			
		}
		return self;
	}


@end
