/*
	YPUpdateUserInfoResponse.h
	The interface definition of properties and methods for the YPUpdateUserInfoResponse object.
	Generated by SudzC.com
*/

#import <Foundation/Foundation.h>


@interface YPUpdateUserInfoResponse : NSObject
{
	NSString* _responseMessage;
	int _statusCode;
	BOOL _valid;
	
}
		
	@property (strong, nonatomic) NSString* responseMessage;
	@property int statusCode;
	@property BOOL valid;

-(void)parsingUpdateUserInfo:(NSDictionary*)dictResponse;

    
    


@end
