/*
	YPUpdateUserInfoRequest.h
	The interface definition of properties and methods for the YPUpdateUserInfoRequest object.
	Generated by SudzC.com
*/

#import <Foundation/Foundation.h>


@interface YPUpdateUserInfoRequest : NSObject
{
	NSString* _DOB;
	NSString* _SC;
	NSString* _applicationType;
	NSString* _city;
	NSString* _country;
	NSString* _emailAddress;
	NSString* _firstName;
	NSString* _lastName;
	NSString* _middleName;
	NSString* _mobilePhoneNumber;
	NSString* _postCode;
	NSString* _region;
	NSString* _sex;
	NSString* _streetAddress1;
	NSString* _streetAddress2;
	NSString* _userName;
	BOOL _valid;
	
}
		
	@property (strong, nonatomic) NSString* DOB;
	@property (strong, nonatomic) NSString* SC;
	@property (strong, nonatomic) NSString* applicationType;
	@property (strong, nonatomic) NSString* city;
	@property (strong, nonatomic) NSString* country;
	@property (strong, nonatomic) NSString* emailAddress;
	@property (strong, nonatomic) NSString* firstName;
	@property (strong, nonatomic) NSString* lastName;
	@property (strong, nonatomic) NSString* middleName;
	@property (strong, nonatomic) NSString* mobilePhoneNumber;
	@property (strong, nonatomic) NSString* postCode;
	@property (strong, nonatomic) NSString* region;
	@property (strong, nonatomic) NSString* sex;
	@property (strong, nonatomic) NSString* streetAddress1;
	@property (strong, nonatomic) NSString* streetAddress2;
	@property (strong, nonatomic) NSString* userName;
	@property BOOL valid;

	

@end
