/*
	YPUpdatePasswordRequest.h
	The interface definition of properties and methods for the YPUpdatePasswordRequest object.
	Generated by SudzC.com
*/

#import <Foundation/Foundation.h>


@interface YPUpdatePasswordRequest : NSObject
{
	NSString* SC;
	NSString* applicationType;
	NSString* nPassword;
	NSString* oldPassword;
	NSString* userName;
	BOOL _valid;
	
}
		
	@property (strong, nonatomic) NSString* SC;
	@property (strong, nonatomic) NSString* applicationType;
	@property (strong, nonatomic) NSString* nPassword;
	@property (strong, nonatomic) NSString* oldPassword;
	@property (strong, nonatomic) NSString* userName;
	@property BOOL valid;


@end
