/*
	YPUpdateUserInfoResponse.h
	The implementation of properties and methods for the YPUpdateUserInfoResponse object.
	Generated by SudzC.com
*/
#import "YPUpdateUserInfoResponse.h"

@implementation YPUpdateUserInfoResponse
	@synthesize responseMessage = _responseMessage;
	@synthesize statusCode = _statusCode;
	@synthesize valid = _valid;

	- (id) init
	{
		if(self = [super init])
		{
			self.responseMessage = nil;

		}
		return self;
	}
-(void)parsingUpdateUserInfo:(NSDictionary*)dictResponse{

    NSLog(@"parsingUpdateUserInfo =   %@",dictResponse);
    
    

}

	
@end
