/*
	YPUpdatePasswordResponse.h
	The interface definition of properties and methods for the YPUpdatePasswordResponse object.
	Generated by SudzC.com
*/

#import <Foundation/Foundation.h>


@interface YPUpdatePasswordResponse : NSObject
{
	NSString* _responseMessage;
	int _statusCode;
	BOOL _valid;
	
}
		
	@property (strong, nonatomic) NSString* responseMessage;
	@property int statusCode;
	@property BOOL valid;
-(void)parsingUpdatePassword:(NSDictionary*)dictResponse;

    
@end
