/*
	YPUpdatePasswordResponse.h
	The implementation of properties and methods for the YPUpdatePasswordResponse object.
	Generated by SudzC.com
*/
#import "YPUpdatePasswordResponse.h"

@implementation YPUpdatePasswordResponse
	@synthesize responseMessage = _responseMessage;
	@synthesize statusCode = _statusCode;
	@synthesize valid = _valid;

	- (id) init
	{
		if(self = [super init])
		{
			self.responseMessage = nil;

		}
		return self;
	}

-(void)parsingUpdatePassword:(NSDictionary*)dictResponse{

    
    NSLog(@"parsingUpdatePassword = %@",dictResponse);
    
    
    self.statusCode=[[[[[dictResponse valueForKey:@"updatePasswordResponse"] valueForKey:@"updatePasswordReturn"] valueForKey:@"statusCode"] valueForKey:@"text"]intValue];
    
    self.responseMessage=[[[[dictResponse valueForKey:@"updatePasswordResponse"] valueForKey:@"updatePasswordReturn"] valueForKey:@"responseMessage"] valueForKey:@"text"];
    
    


}

@end