/*
	YPUpdateUserInfoRequest.h
	The implementation of properties and methods for the YPUpdateUserInfoRequest object.
	Generated by SudzC.com
*/
#import "YPUpdateUserInfoRequest.h"

@implementation YPUpdateUserInfoRequest
	@synthesize DOB = _DOB;
	@synthesize SC = _SC;
	@synthesize applicationType = _applicationType;
	@synthesize city = _city;
	@synthesize country = _country;
	@synthesize emailAddress = _emailAddress;
	@synthesize firstName = _firstName;
	@synthesize lastName = _lastName;
	@synthesize middleName = _middleName;
	@synthesize mobilePhoneNumber = _mobilePhoneNumber;
	@synthesize postCode = _postCode;
	@synthesize region = _region;
	@synthesize sex = _sex;
	@synthesize streetAddress1 = _streetAddress1;
	@synthesize streetAddress2 = _streetAddress2;
	@synthesize userName = _userName;
	@synthesize valid = _valid;

	- (id) init
	{
		if(self = [super init])
		{
			self.DOB = nil;
			self.SC = nil;
			self.applicationType = nil;
			self.city = nil;
			self.country = nil;
			self.emailAddress = nil;
			self.firstName = nil;
			self.lastName = nil;
			self.middleName = nil;
			self.mobilePhoneNumber = nil;
			self.postCode = nil;
			self.region = nil;
			self.sex = nil;
			self.streetAddress1 = nil;
			self.streetAddress2 = nil;
			self.userName = nil;

		}
		return self;
	}

	

@end
