/*
	YPUserInfoRequest.h
	The implementation of properties and methods for the YPUserInfoRequest object.
	Generated by SudzC.com
*/
#import "YPUserInfoRequest.h"

@implementation YPUserInfoRequest
	@synthesize SC = _SC;
	@synthesize applicationType = _applicationType;
	@synthesize userName = _userName;
	@synthesize valid = _valid;

	- (id) init
	{
		if(self = [super init])
		{
			self.SC = nil;
			self.applicationType = nil;
			self.userName = nil;

		}
		return self;
	}

	

@end
